name = "burst-registry"
main = "worker.ts"
compatibility_date = "2026-05-21"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "burst-registry"
database_id = "3a5a834b-9ce2-48a1-b2d2-8f2375536125"
